---
title: "About Steph"
description: |
  Here's a bit about my background and recent projects!
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

I'm a writer, researcher, and composer currently living in Pennsylvania. I will be graduating from George Washington University this May, with a BA in Religious Studies and minors in Psychological & Brain Sciences and Journalism & Mass Communication. Some of my writing has recently been published in *Just Place Chapbook*, *Capitol Letters*, *The Ekphrastic Review*, *The Rival GW*, and in the anthology *Falling Leaves* published by Day Eight.

I will begin my MPhil in Theology at the University of Oxford this fall, concentrating in modern theology, religion, and science. My research focuses on contemporary neuroscientific findings involving preconscious and conscious processing, decision-making, and self-identity in relationship with historical concepts of free will, selfhood, and subjectivity in philosophy and theology.

I am also a composer and arranger, and some of my recent projects are posted on my [Musescore dashboard](https://musescore.com/user/4910116/sheetmusic).

Across disciplines and genres, all of my work is motivated by the unique power of art and writing to ask meaningful questions and inspire authenticity.
