---
title: "Science Journalism Feature"
description: |
  This piece is the final feature story I wrote for science journalism in spring 2020.
author:
  - name: Steph Gemmell
    url: {}
date: 04-26-2021
output:
  distill::distill_article:
    self_contained: false
categories: 
  - smpa
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**Hospital chaplains work toward "healing and wholeness"**

*Spiritual support impacts the health of patients and healthcare providers*

· · ·

"There were times when I would walk into a room, and I could look into the doctor's eyes and it would look like they were saying, 'oh, what are *you* doing here?'" Dennis Schell recalled.

As a hospital chaplain in Wichita, Kansas in the 1970s, Schell regularly encountered physicians who thought spirituality had no place in healthcare. While the healthcare system has gradually embraced the intersections of spirituality and health in the last few decades, Schell said that dismissive views of spirituality still persist in medicine and psychology.

"I always felt that there was a positive aspect to religion and spirituality that healthcare and psychology often put down," Schell said. After working as a chaplain and Lutheran minister, Schell found it easy to transition from pastoral counseling to psychology. Now a psychologist at George Washington University, Schell teaches about the intersections of spirituality, psychology, and health. He said that despite a growing body of research associating spiritual support with better patient outcomes, the process of integrating spiritual support in patient care has been slow.

"From a mental health point of view, there are still quite a few psychiatrists and psychologists that basically say, 'religion has no place here,'" Schell explained. "There are physicians that could care less, and in many cases physicians that don't want anything to do with [spirituality], and they don't believe it has any place whatsoever in a medical profession. There is often a negative stereotype against religious practitioners in the healthcare system."

Christy DiFrances Remein, a clinical assistant professor of medicine at George Washington University, suggested that hesitancy within the healthcare system to integrate spiritual support in patient care traces back to the standardization of medical education in the early twentieth century. The Flexner Report,
published in 1910, established vital standards for medical education in the U.S. and Canada. But DiFrances Remein said that an "unfortunate repercussion" of the report was a shift away from the integration of spiritual, emotional, and psychosocial health in medicine.

"The focus became so strong on the scientific competencies and biomedical competencies," DiFrances Remein explained. "The more holistic side of medical education kind of disappeared."

Persistent negative views of religion and spirituality in the healthcare system have consequences for patient access to spiritual support. In 2005, researchers [found](https://journals.sagepub.com/doi/abs/10.2190/9X2X-QQEU-GDE9-VUXN?casa_token=QYs6xWoGxYIAAAAA:pcRaHtmbmxDklfx8odLbarNcQFfaz-_NBMiqbX0aH3vDJ5Kg6lf1O9ygsm-n3_YgVEN0g9LrzHw) that 72 percent of patients being treated in leading hospitals in the U.S. reported that their spiritual needs were "minimally or not at all met" by the healthcare system. The researchers estimated that only about 20 percent of hospitalized patients receive visits from chaplains. More recent [research](https://academic.oup.com/sw/article-abstract/56/4/306/1871337) also shows that, although addressing patients' spiritual needs has been shown to correspond with better health outcomes, those needs often go unaddressed in healthcare settings.

Dr. Harold Koenig, a psychiatrist at Duke University and cofounder of the Duke Center for Spirituality, Theology and Health, said that chaplains should be viewed as an integral part of healthcare teams.

"If people have spiritual or religious concerns, there is no one in the healthcare system who can address those concerns other than the chaplain," Koenig explained. "Lots of people turn to their religious faiths when they get sick, especially when they feel out of control as people do when they get admitted to the hospital. They may also have religious or spiritual struggles that may adversely affect their health, unless they are dealt with by someone who is skilled in doing so."

Chaplains receive specialized training that prepares them to provide support to people from any religious background or no religious background at all. Clinical chaplains complete a training program called clinical pastoral education (CPE), typically as part of a master's degree. During CPE, chaplaincy residents work alongside certified chaplains in settings like hospitals, nursing homes and rehabilitation facilities. The intense experiences that chaplaincy residents encounter during CPE can help them to determine whether they want to pursue chaplaincy long-term.

Katherine Chatelaine-Samsen, a Lutheran pastor in Washington, D.C., completed a full-time, 12-week unit of CPE as part of her ordination process. She explained that candidates for chaplaincy certification complete several more units of CPE, including a residency. Chatelaine-Samsen said that the CPE curriculum incorporates psychology and behavioral science to provide chaplains with the resources to support patients from a variety of backgrounds.

"My supervisory group was multi-faith, and the patients we saw were of many faith backgrounds and no faith backgrounds," Chatelaine-Samsen noted. "We were trained to meet the patients where they were on their spiritual journey."

The first CPE training program launched in 1925 with the goal of providing chaplains with practical education and experience in clinical settings. More than 300 CPE programs are now accredited by [ACPE](https://www.acpe.edu/ACPE/About_ACPE/ACPE/About_ACPE/About_ACPE.aspx), an organization that oversees the certification of pastoral counselors and spiritually integrated psychotherapists.

"A common misconception about contemporary professional healthcare chaplains is that we are trained to preach to the sick about God," said Elizabeth Berger, a Jewish chaplain and narrative medicine consultant in the New York City area. "In fact, the focus of clinical pastoral education is the cultivation of a specific kind of acuity: an ability to accompany patients, families and staff across all belief systems by reading the subtleties of human interaction."

Chaplains play a multifaceted role in the healthcare system, providing support to both patients and their doctors. Chaplains typically counsel dying patients, offer support to patients experiencing emotional problems, and provide pastoral counseling before and after surgeries. Hospital chaplains also offer grief counseling to families and provide patients' relatives with other spiritual and emotional support. Chaplains can help to bridge the gap between doctors and patients by encouraging patients to follow their treatment plans and addressing religious or spiritual issues that may interfere with the treatment process, Dennis Schell said. Schell emphasized that the psychological benefits of spiritual support can also benefit patients' physical health.

"We now know after more than 30 years of research that there is a relationship between stress and illness," Schell explained. "If spirituality or spiritual support systems can help manage stress, then that can lead to people helping to manage an illness."

The body's stress response originates in the hypothalamus, an almond-sized structure nestled in the base of the forebrain. Through the pituitary gland, the hypothalamus sends signals to the endocrine system, linking mind and body to control the release of hormones into the circulatory system. [Research](https://science.sciencemag.org/content/270/5234/232) has shown that hormones associated with stress, like cortisol and catecholamine, suppress the body's immune functions. These findings suggest that heightened stress during hospitalization can leave patients more vulnerable to infection.

Scientists have [identified](https://psycnet.apa.org/record/1999-15342-002) an association between a higher sense of coherence---a perception of life events as being meaningful---and a lower susceptibility to stress-induced immunity changes. [Research](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.322.7375&rep=rep1&type=pdf) has also historically shown an association between loneliness and a weakened immune response. Having access to spiritual and social support can offer patients "hope and direction at a time when uncertainty abounds," Harold Koenig said.

"Consequently, their bodies are going to respond more quickly to medical treatments," Koenig explained.

In addition to counseling patients, chaplains can also provide doctors and nurses with vital support, Elizabeth Berger said.

"Whether or not they believe in a divine being, healthcare professionals often feel a special calling to their work," Berger explained. "Because they are so highly motivated to sustain life, death can be seen as tantamount to personal failure---they take it very hard."

Berger noted that COVID-19 has intensified the challenges that healthcare teams face on a regular basis, making the support that chaplains offer even more crucial.

"A chaplain's presence signals cultural permission for healthcare team members to attend to their spiritual health in whatever ways they find meaningful," Berger said. "A professional chaplain's ability to help the staff engage with connectedness and meaning-making according to their own belief systems is especially important to helping combat burnout right now."

In recent years, healthcare systems have gradually reintroduced spiritual support as part of patient care. Christy DiFrances Remein works with the [GW Institute for Spirituality and Health](https://smhs.gwu.edu/gwish/) (GWish), an organization that seeks to bring attention to the importance of addressing the spiritual needs of both patients and healthcare professionals. The organization supports "multidisciplinary healthcare teams" that include chaplains and clergy members. GWish also focuses on promoting awareness of the positive role spirituality can play in the healthcare system.

"There are still a lot of people who flinch at spirituality," DiFrances Remein noted. "There's still an idea that there's some kind of split between science and any kind of spirituality, and that's really a false dichotomy."
